name: caritas_donation_app
description: A new Flutter project.
version: 1.2.1

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  get_it: ^8.0.3
  logger: ^1.0.0
  smooth_page_indicator: ^1.2.0
  flutter_web_plugins:
    sdk: flutter
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/