name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: stable

    - name: Verify Flutter installation
      run: flutter doctor -v

    - name: Install dependencies
      run: flutter pub get

    - name: Build web app
      run: flutter build web --release

    - name: Update base href in index.html
      run: sed -i 's|\$FLUTTER_BASE_HREF|https://jardar-tomra.github.io/my_flutter_project/|g' build/web/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
