name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: stable

    - name: Verify Flutter installation
      run: flutter doctor -v

    - name: Install dependencies
      run: flutter pub get

    - name: Build web app
      run: flutter build web --release --base-href "$FLUTTER_BASE_HREF"
      env:
        FLUTTER_BASE_HREF: "/${{ github.event.repository.name }}/"

    - name: Embed version into index.html
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
        sed -i "s|<head>|<head><meta name='version' content='$VERSION'>|" build/web/index.html

    - name: Create .nojekyll file
      run: echo > build/web/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
